table dim_city
	lineageTag: a4a971c2-4576-44de-a7cd-44ed408ab7fc

	column region_id
		dataType: int64
		formatString: 0
		lineageTag: e68d77d0-4b15-44de-a02c-09dc4608cd75
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column city_id
		dataType: int64
		formatString: 0
		lineageTag: d680e398-81b5-42dc-87c4-6a63e8cba961
		summarizeBy: none
		sourceColumn: city_id

		annotation SummarizationSetBy = Automatic

	column city_name
		dataType: string
		lineageTag: 8a7db422-7cad-4dff-831e-18ac2413b808
		summarizeBy: none
		sourceColumn: city_name

		annotation SummarizationSetBy = Automatic

	partition dim_city = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents(CSV_DIR & "dim_city.csv"),[Delimiter=";", Columns=3, Encoding=1252]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"city_id", Int64.Type}, {"region_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

